[server]
listen = "0.0.0.0"
port = 6666
tls_listen = "0.0.0.0"
tls_port = 6443
tls_key_file = ""
tls_cert_file = ""
tls_auth_client = false
tls_ca_cert_file = ""
pd_addrs = "127.0.0.1:2379"
instance_id = "1"
prometheus_listen = "0.0.0.0"
prometheus_port = 8080
log_level = "debug"
log_file = "tikv-service.log"

[backend]
use_txn_api = true
use_async_commit = true
try_one_pc_commit = true
use_pessimistic_txn = true
local_pool_number = 4
txn_retry_count = 10
txn_region_backoff_delay_ms = 2
txn_region_backoff_delay_attemps = 2
txn_lock_backoff_delay_ms = 2
txn_lock_backoff_delay_attemps = 5
